Feature/combine insights download publish
quipucords/qpc pull request #204
Opened 2022-09-08 10:34 UTC by nicolearagao

Add new argument --report to InsightsPublishCommand which downloads the
 insights report from qpc server and publishes it to insights.
 
Implementation of DISCOVERY-170

2022-09-08 15:19 UTC, bruno-fs requested changes
It's good but has some unnecessary extra code.

2022-09-12 18:35 UTC, bruno-fs commented on qpc/insights/tests_insights_publish.py
> +        mock_validate_report_content.assert_called_with(str(payload_file))
is this working? :open_mouth: 

it should be throwing a NameError :scream:

2022-09-12 22:31 UTC, bruno-fs approved these changes

2022-09-20 12:03 UTC, gtanzillo approved these changes
Looks Great! Thanks @nicolearagao

2022-09-21 21:07 UTC, merged