POC support for ansible controller
quipucords/qpc pull request #217
Opened 2023-02-08 18:17 UTC by bruno-fs

2023-04-10 15:39 UTC, abellotti approved these changes

2023-04-10 15:40 UTC, abellotti commented
LGTM!! 👍

2023-04-10 16:12 UTC, nicolearagao approved these changes
LGTM 👍🏼

2023-04-10 16:49 UTC, infinitewarp approved these changes

2023-04-10 17:10 UTC, ruda requested changes
Hope you like this suggestions to update the help messages.

2023-04-10 17:32 UTC, nicolearagao commented on qpc/cred/add.py
>              help=_(messages.CRED_TYPE_HELP),
Hey @ruda, we will address this soon. We have a jira ticket open for this issue: https://issues.redhat.com/browse/DISCOVERY-211. We will create a new one to make sure to include info about Ansible as well.

2023-04-10 18:31 UTC, bruno-fs commented on qpc/cred/add.py
>              help=_(messages.CRED_TYPE_HELP),
DISCOVERY-211 covers only manpage, not help text (and is ocp related).

I'm aligned with rudá on this one, it's better if we have it done.

2023-04-10 18:35 UTC, nicolearagao commented on qpc/cred/add.py
>              help=_(messages.CRED_TYPE_HELP),
I see, thanks for clarifying. I thought an overall update was covered by that issue.

2023-04-10 19:19 UTC, bruno-fs commented on qpc/cred/add.py
>              help=_(messages.CRED_TYPE_HELP),
done.
notice I'm introducing a breaking change to the "OCP_TOKEN" message (should not be married to OCP anyways. nothing holds us from using in another integration in the future   (satellite and ansible do have support for that)

2023-04-11 13:42 UTC, ruda approved these changes
Perfect! LGTM.

2023-04-11 13:43 UTC, merged